# Generated by Django 3.2.16 on 2022-12-27 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adobesign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturetype',
            name='api_root_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='AdobeSign region-specific api root url (will be filled from the API)'),
        ),
        migrations.AlterField(
            model_name='signaturetype',
            name='signature_backend_code',
            field=models.CharField(choices=[], db_index=True, max_length=50, verbose_name='signature backend'),
        ),
        migrations.AlterField(
            model_name='signaturetype',
            name='web_root_url',
            field=models.CharField(default='https://secure.na2.echosign.com', max_length=255, verbose_name='AdobeSign web root url (on the shard where your oauth app is defined)'),
        ),
    ]
