version: 2
jobs:
  lint:
    docker:
      - image: python:3.8

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pip install tox
            tox -e 'flake8' -vv

  test-python36:
    docker:
      - image: python:3.6

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pip install tox
            tox -e 'py36-django{22}'

  test-python37:
    docker:
      - image: python:3.7

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pip install tox
            tox -e 'py37-django{22}'

  test-python38:
    docker:
      - image: python:3.8

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            pip install tox
            tox -e 'py38-django{22}'

workflows:
  default:
    jobs:
      - lint
      - test-python36:
          requires:
            - lint
      - test-python37:
          requires:
            - lint
      - test-python38:
          requires:
            - lint
  version: 2
